package com.example.hello;

import java.io.PrintStream;
import java.lang.Integer;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.StringBuilder;
import java.lang.System;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;
import java.util.function.Consumer;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * <h3>Generated by <a href="https://github.com/h908714124/jbock">jbock 4.1.001</a></h3>
 * <p>Use the default constructor to obtain an instance of this parser.</p>
 */
final class DeleteCommand_Parser {
  private static final Map<String, Option> OPTIONS_BY_NAME = optionsByName();

  private static final Pattern SUSPICIOUS = Pattern.compile("-[a-zA-Z0-9]+|--[a-zA-Z0-9-]+");

  private PrintStream err = System.err;

  private String programName = "delete-command";

  private int terminalWidth = 80;

  private Consumer<ParseResult> exitHook = result ->
    System.exit(result instanceof HelpRequested ? 0 : 1);

  private Map<String, String> messages = Collections.emptyMap();

  /**
   * This parse method has no side effects.
   * Consider {@link #parseOrExit()} instead which does standard error-handling
   * like printing error messages, and potentially shutting down the JVM.
   */
  ParseResult parse(String[] args) {
    if (args.length == 0)
      return new HelpRequested();
    if (args.length == 1 && ("--help".equals(args[0]) || "-h".equals(args[0])))
      return new HelpRequested();
    StatefulParser state = new StatefulParser();
    Iterator<String> it = Arrays.asList(args).iterator();
    try {
      DeleteCommand result = state.parse(it);
      return new ParsingSuccess(result);
    }
    catch (RuntimeException e) {
      return new ParsingFailed(e);
    }
  }

  DeleteCommand parseOrExit(String[] args) {
    ParseResult result = parse(args);
    if (result instanceof ParsingSuccess)
      return ((ParsingSuccess) result).getResult();
    if (result instanceof HelpRequested) {
      printOnlineHelp();
      err.flush();
      exitHook.accept(result);
      throw new RuntimeException("help requested");
    }
    err.println("Error: " + ((ParsingFailed) result).getError().getMessage());
    printTokens("        ", usage());
    err.println("Try '" + programName + " --help' for more information.");
    err.flush();
    exitHook.accept(result);
    throw new RuntimeException("parsing error");
  }

  DeleteCommand_Parser withProgramName(String programName) {
    this.programName = programName;
    return this;
  }

  DeleteCommand_Parser withTerminalWidth(int width) {
    this.terminalWidth = width == 0 ? this.terminalWidth : width;
    return this;
  }

  DeleteCommand_Parser withMessages(Map<String, String> map) {
    this.messages = map;
    return this;
  }

  DeleteCommand_Parser withExitHook(Consumer<ParseResult> exitHook) {
    this.exitHook = exitHook;
    return this;
  }

  DeleteCommand_Parser withErrorStream(PrintStream err) {
    this.err = err;
    return this;
  }

  void printOnlineHelp() {
    err.println("USAGE");
    printTokens("        ", usage());
    err.println();
    err.println("PARAMETERS");
    printOption(Option.PATH, "", "  PATH ");
    err.println();
    err.println("OPTIONS");
    printOption(Option.VERBOSITY, "", "  --verbosity VERBOSITY ");
  }

  private void printOption(Option option, String messageKey, String names) {
    String message = messageKey.isEmpty() ? null : messages.get(messageKey);
    List<String> tokens = new ArrayList<>();
    tokens.add(names);
    tokens.addAll(Optional.ofNullable(message)
          .map(String::trim)
          .map(s -> s.split("\\s+", -1))
          .map(Arrays::asList)
          .orElseGet(() -> Arrays.stream(option.description)
            .map(s -> s.split("\\s+", -1))
            .flatMap(Arrays::stream)
            .collect(Collectors.toList())));
    String continuationIndent = String.join("", Collections.nCopies(names.length() + 1, " "));
    printTokens(continuationIndent, tokens);
  }

  private void printTokens(String continuationIndent, List<String> tokens) {
    List<String> lines = makeLines(continuationIndent, tokens);
    for (String line : lines)
      err.println(line);
  }

  private List<String> makeLines(String continuationIndent, List<String> tokens) {
    List<String> result = new ArrayList<>();
    StringBuilder line = new StringBuilder();
    int i = 0;
    while (i < tokens.size()) {
      String token = tokens.get(i);
      boolean fresh = line.length() == 0;
      if (!fresh && token.length() + line.length() + 1 > terminalWidth) {
        result.add(line.toString());
        line.setLength(0);
        continue;
      }
      if (i > 0) {
        line.append(fresh ? continuationIndent : " ");
      }
      line.append(token);
      i++;
    }
    if (line.length() > 0) {
      result.add(line.toString());
    }
    return result;
  }

  private List<String> usage() {
    List<String> result = new ArrayList<>();
    result.add(" ");
    result.add(programName);
    result.add("[OPTION]...");
    result.add("PATH");
    return result;
  }

  private static String readOptionArgument(String token, Iterator<String> it) {
    if (token.charAt(1) == '-' && token.indexOf('=') >= 0)
      return token.substring(token.indexOf('=') + 1);
    if (token.charAt(1) != '-' && token.length() >= 3)
      return token.substring(2);
    if (!it.hasNext())
      throw new RuntimeException("Missing value after token: " + token);
    return it.next();
  }

  private static Map<String, Option> optionsByName() {
    Map<String, Option> result = new HashMap<>(1);
    result.put("--verbosity", Option.VERBOSITY);
    return result;
  }

  private static Map<Option, OptionParser> optionParsers() {
    Map<Option, OptionParser> parsers = new EnumMap<>(Option.class);
    parsers.put(Option.VERBOSITY, new RegularOptionParser(Option.VERBOSITY));
    return parsers;
  }

  private static RuntimeException missingRequired(String name) {
    return new RuntimeException("Missing required: " + name);
  }

  private static class StatefulParser {
    boolean endOfOptionParsing;

    Map<Option, OptionParser> optionParsers = optionParsers();

    String[] paramParsers = new String[1];

    DeleteCommand parse(Iterator<String> it) {
      int position = 0;
      while (it.hasNext()) {
        String token = it.next();
        if (!endOfOptionParsing && "--".equals(token)) {
          endOfOptionParsing = true;
          continue;
        }
        if (tryParseOption(token, it)) {
          continue;
        }
        if (!endOfOptionParsing) {
          if (SUSPICIOUS.matcher(token).matches())
            throw new RuntimeException("Invalid option: " + token);
        }
        if (position == 1)
          throw new RuntimeException("Excess param: " + token);
        paramParsers[position++] = token;
      }
      return build();
    }

    boolean tryParseOption(String token, Iterator<String> it) {
      if (endOfOptionParsing)
        return false;
      Option option = tryReadOption(token);
      if (option == null)
        return false;
      optionParsers.get(option).read(token, it);
      return true;
    }

    Option tryReadOption(String token) {
      if (token.length() <= 1 || token.charAt(0) != '-')
        return null;
      if (token.charAt(1) != '-')
        return OPTIONS_BY_NAME.get(token.substring(0, 2));
      int index = token.indexOf('=');
      if (index < 0)
        return OPTIONS_BY_NAME.get(token);
      return OPTIONS_BY_NAME.get(token.substring(0, index));
    }

    DeleteCommand build() {
      return new DeleteCommandImpl(
          optionParsers.get(Option.VERBOSITY).stream()
            .map(Integer::valueOf)
            .findAny(),
          Optional.ofNullable(paramParsers[0])
            .map(Paths::get)
            .orElseThrow(() -> missingRequired("PATH")));
    }
  }

  private enum Option {
    VERBOSITY("A named option."),

    PATH("A positional parameter.");

    String[] description;

    Option(String... description) {
      this.description = description;
    }
  }

  private static class DeleteCommandImpl extends DeleteCommand {
    OptionalInt verbosity;

    Path path;

    DeleteCommandImpl(Optional<Integer> verbosity, Path path) {
      this.verbosity = verbosity.isPresent() ? OptionalInt.of(verbosity.get()) : OptionalInt.empty();
      this.path = path;
    }

    OptionalInt verbosity() {
      return verbosity;
    }

    Path path() {
      return path;
    }
  }

  private abstract static class OptionParser {
    final Option option;

    OptionParser(Option option) {
      this.option = option;
    }

    abstract void read(String token, Iterator<String> it);

    abstract Stream<String> stream();
  }

  private static class RegularOptionParser extends OptionParser {
    String value;

    RegularOptionParser(Option option) {
      super(option);
    }

    void read(String token, Iterator<String> it) {
      if (value != null)
        throw new RuntimeException(String.format("Option '%s' is a repetition", token));
      value = readOptionArgument(token, it);
    }

    Stream<String> stream() {
      return value == null ? Stream.empty() : Stream.of(value);
    }
  }

  abstract static class ParseResult {
    private ParseResult() {
    }
  }

  static final class ParsingFailed extends ParseResult {
    private final RuntimeException error;

    private ParsingFailed(RuntimeException error) {
      this.error = error;
    }

    RuntimeException getError() {
      return error;
    }
  }

  static final class ParsingSuccess extends ParseResult {
    private final DeleteCommand result;

    private ParsingSuccess(DeleteCommand result) {
      this.result = result;
    }

    DeleteCommand getResult() {
      return result;
    }
  }

  static final class HelpRequested extends ParseResult {
  }
}
